### ISSUE TITLE
Wrong dependency in package.json

### ISSUE THREAD

**Issue by bkrieger1991** [ng-tools/generator-ng-factory#4]
Hello,

it seems that the generated "package.json" for angular-components gets a wrong dependency.

Reproduction: after a clean install via "yo ng-factory" and the question "What are you building today?" answered with "component" the undertaker-dependency is: "undertaker-app-tasks": "^0.2".

This leads to an error if you try to run a gulp-task (serve or build): 
Error: Bower components directory does not exist at /path/to/your/project//app/bower_components

Well, changed this dependency to "undertaker-lib-tasks": "^0.3" resolves this error and builds the project the right way, without any issue.

Hope this detail can help make it even better ;)

**Comment by mgcrea** [comment]
@bkrieger1991 Thanks for the report ;-)!
